# Generated by Django 5.1.6 on 2025-02-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0002_myuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
