# Generated by Django 5.1.6 on 2025-02-27 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myform', '0004_myuser_address_myuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
    ]
